version: "3"

services:
  dev:
      container_name: instrument_rest_api_dev
      image: instrument_rest_api_dev:1.0.0
      build:
        context: .
        target: development
        dockerfile: ./Dockerfile
      command: npm run start:debug
      ports:
        - 3000:3000
      networks:
        - nesjs-network
      volumes:
        - .:/usr/src/app
        - /usr/src/app/node_modules
      restart: unless-stopped

networks:
  nesjs-network:
